### PR TITLE
Fix downstreamproxy for HTTP CONNECT

### PR DESCRIPTION
**Pull request by netroby**
Signed-off-by: huzhifeng <huzhifeng@douyu.tv>

### CODE REVIEW

**Comment by netroby** [comment]
See https://github.com/google/martian/issues/213

**Comment by netroby** [comment]
ping @bramhaghosh @cpasillas

**Comment by netroby** [comment]
@davidkeay  hello, would you please take a look?

**Comment by admtnnr** [comment]
Fixed by #215

**Comment by bramhaghosh** [comment]
Fixed by #215

**Pull request closed without merging**
